
using System.Collections;
using System.Collections.Generic;
using Unity.VisualScripting;
using UnityEngine;

public class PlayerController : MonoBehaviour
{
    public float moveSpeed = 5f;
    public Transform movePoint;
    private int count = 0;

    public LayerMask whatStopsMovement;
    public LayerMask encounterZone;

    // Start is called before the first frame update
    void Start()
    {
        //remove movepoint from parent so that movepoint position is not relative to the player
        movePoint.parent = null;
    }

    // Update is called once per frame
    void Update()
    {
        var moved = MoveMovepoint();
        if (moved)
        {
            EventManager.PlayerMoved();
        }
    }

    private void FixedUpdate()
    {
        MovePlayer();
    }

    private bool MoveMovepoint()
    {
        if (Vector3.Distance(transform.position, movePoint.position) <= .05f)
        {
            if (Mathf.Abs(Input.GetAxisRaw("Horizontal")) == 1f)
            {
                if (!Physics2D.OverlapCircle(movePoint.position + new Vector3(Input.GetAxisRaw("Horizontal"), 0f, 0f), .2f, whatStopsMovement))
                {
                    movePoint.position += new Vector3(Input.GetAxisRaw("Horizontal"), 0f, 0f);
                    return true;
                }
            }

            if (Mathf.Abs(Input.GetAxisRaw("Vertical")) == 1f)
            {
                if (!Physics2D.OverlapCircle(movePoint.position + new Vector3(0f, Input.GetAxisRaw("Vertical"), 0f), .2f, whatStopsMovement))
                {
                    movePoint.position += new Vector3(0f, Input.GetAxisRaw("Vertical"), 0f);
                    return true;
                }
            }
        }
        return false;
    }

    private void MovePlayer()
    {
        transform.position = Vector3.MoveTowards(transform.position, movePoint.position, moveSpeed * Time.deltaTime);
    }
}